name: documentation-generation
on: [push]
jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: "Doxygen"
        run: |
          pwd
          ls
          sudo apt-get install -y doxygen
          doxygen docs/doxyfile
